name: Ozzy
favicon: null
layout_spectrum: 1
title: Scrapbook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose:
  - name: engagement
    item: null
    url: null
